PediatricTattooServer/config/routes.rb
Rails.application.routes.draw do
  root 'patients#new'

  resources :patients do
    get :generate_pdf, on: :member
  end
  resources :pain_logs

  namespace :api do
  	resources :patients do
    	get :search, on: :collection
    	get :pain_log, on: :member
    end
    resources :pain_logs
  end
end

PediatricTattooServer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

PediatricTattooServer/app/models/pain_log.rb
class PainLog < ActiveRecord::Base
	belongs_to :patient, inverse_of: :pain_logs

	validates :body_part, :pain_level, presence: true
end

PediatricTattooServer/app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :pain_logs, inverse_of: :patient
	has_attached_file :bio_pic, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

	validates :name, presence: true
	validates_attachment_content_type :bio_pic, content_type: /\Aimage\/.*\z/
end

PediatricTattooServer/app/controllers/api/pain_logs_controller.rb
class PainLogsController < ApplicationController
	before_action :prepare_pain_log, only: [:show, :update, :destroy]

	def index
		@pain_logs = PainLog.all
		render json: @pain_logs
	end

	def show
		render json: @pain_log
	end

	def new
		@pain_log = PainLog.new
	end

	def create
		@pain_log = PainLog.new(patient_params)
	    if @pain_log.save
	      render json: @pain_log
	    else
	      render json: { errors: @pain_log.errors.full_messages }
	    end
	end

	def update
		if @pain_log.update(patient_params)
	      render json: @pain_log
	    else
	      render json: { errors: @pain_log.errors.full_messages }
	    end
	end

	def destroy
		@pain_log.destroy
	    render json: { success: "true" }
	  rescue ActiveRecord::InvalidForeignKey
	    render json: { errors: "this patient is in use by other things" }
	end

	private

	def prepare_patient
		@pain_log = Patient.find(params[:id])
	end

	def patient_params
		params.require(:pain_log).permit(:body_part, :pain_level, :patient_id)
	end
end

PediatricTattooServer/app/controllers/api/patients_controller.rb
class PatientsController < ApplicationController
	before_action :prepare_patient, only: [:show, :update, :destroy, :pain_log]

	def index
		@patients = Patient.all
		render json: @patients
	end

	def show
		render json: @patient
	end

	def new
		@patient = Patient.new
	end

	def create
		@patient = Patient.new(patient_params)
	    if @patient.save
	      render json: @patient
	    else
	      render json: { errors: @patient.errors.full_messages }
	    end
	end

	def update
		if @patient.update(patient_params)
	      render json: @patient
	    else
	      render json: { errors: @patient.errors.full_messages }
	    end
	end

	def destroy
		@patient.destroy
	    render json: { success: "true" }
	  rescue ActiveRecord::InvalidForeignKey
	    render json: { errors: "this patient is in use by other things" }
	end

	def search
		@patient = Patient.find_by(ble_id: params[:ble_id])
		render json: @patient
	end

	def pain_log
		@pain_log = @patient.pain_logs
		render json: @pain_log
	end

	private

	def prepare_patient
		@patient = Patient.find(params[:id])
	end

	def patient_params
		params.require(:patient).permit(:name, :ble_id, :doctor)
	end
end

PediatricTattooServer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery unless: -> { request.format.json? }
end

PediatricTattooServer/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	before_action :prepare_patient, only: [:show, :update, :destroy, :pain_log, :generate_pdf]

	def index
		@patients = Patient.all
	end

	def show
		respond_to do |format|
	      format.html
	      format.pdf do
	        render :pdf => "report", :layout => 'pdf.html.slim'
	      end
	    end
	end

	def new
		@patient = Patient.new
	end

	def create
		@patient = Patient.new(patient_params)
	    if @patient.save
	      render json: @patient
	    else
	      render json: { errors: @patient.errors.full_messages }
	    end
	end

	def update
		if @patient.update(patient_params)
	      render json: @patient
	    else
	      render json: { errors: @patient.errors.full_messages }
	    end
	end

	def destroy
		@patient.destroy
	    render json: { success: "true" }
	  rescue ActiveRecord::InvalidForeignKey
	    render json: { errors: "this patient is in use by other things" }
	end

	def search
		@patient = Patient.find_by(ble_id: params[:ble_id])
		render json: @patient
	end

	def pain_log
		@pain_log = @patient.pain_logs
		render json: @pain_log
	end

	def generate_pdf
	end

	private

	def prepare_patient
		@patient = Patient.find(params[:id])
	end

	def patient_params
		params.require(:patient).permit(:name, :ble_id, :doctor, :bio_pic, :address, :email, :gender, :phone)
	end
end

PediatricTattooServer/app/helpers/application_helper.rb
module ApplicationHelper
end

PediatricTattooServer/app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  body

    == yield

PediatricTattooServer/app/views/layouts/pdf.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    / = stylesheet_link_tag "application"
    / = javascript_include_tag "application", "data-turbolinks-track" => true
    = wicked_pdf_stylesheet_link_tag "application"
    = wicked_pdf_javascript_include_tag "application"
    = csrf_meta_tag

  body

    == yield

PediatricTattooServer/app/views/pain_logs/new.html.erb
<h1>New Pain Log :(</h1>

<%= form_for @pain_log do |f| %>
	<%= f.label :body_part %>
	<%= f.text_field :body_part %><br />

	<%= f.label :patient_id %>
	<%= f.number_field :patient_id %><br />

	<%= f.label :pain_level %>
	<%= f.number_field :pain_level %><br />

	<%= f.submit %>
<% end %>

PediatricTattooServer/app/views/patients/new.html.slim
.expanded.row
  .top-bar
  	.top-bar-left
      ul.dropdown-menu
        li.menu-text So and So Hospital

.row
  = simple_form_for @patient do |f|
  	= f.input :name
  	= f.input :ble_id
  	= f.input :doctor
    = f.input :address
    = f.input :phone
    = f.input :gender
    = f.input :email
    = f.input :problems, multiple: true, as: :text
    = f.input :medications, multiple: true, as: :text
    = f.input :bio_pic, as: :file

  	= f.submit

PediatricTattooServer/app/views/patients/show.html.slim
.expanded.row
  .top-bar
  	.top-bar-left
      ul.dropdown-menu
        li.menu-text MIT Medical

.row
  .small-6.columns
    = image_tag @patient.bio_pic
  .small-6.columns
    h2 = @patient.name
    table
      tr
        td Attending doctor
        td = @patient.doctor
      tr
        td Patient ID
        td = @patient.id
      tr
        td Address
        td = @patient.address
      tr
        td Phone
        td = @patient.phone
      tr
        td Gender
        td = @patient.gender
      tr
        td Email
        td = @patient.email

.row
  .small-6.columns
    h3 Problems
    ul
      li Problem 1
      li Lorem Ipsum
      li Dolor Sit Amet
  .small-6.columns
    h3 Medications
    ul
      li Med 1
      li Med 2
      li Med 3

.row
  .small-12.columns
    h3 Report Log
    table
      thead
        tr
          th Body Part
          th Pain Level
          th Time
      - @pain_log.each do |t|
        tr
          td = t.body_part
          td = t.pain_level
          td = t.created_at

PediatricTattooServer/app/views/patients/show.pdf.slim
.expanded.row
  .top-bar
  	.top-bar-left
      ul.dropdown-menu
        li.menu-text MIT Medical
        li = link_to 'Download Report', patient_path(id: @patient.id,format: 'pdf')

.row
  .small-6.columns
    = wicked_pdf_image_tag @patient.bio_pic
  .small-6.columns
    h2 = @patient.name
    table
      tr
        td Attending doctor
        td = @patient.doctor
      tr
        td Patient ID
        td = @patient.id
      tr
        td Address
        td = @patient.address
      tr
        td Phone
        td = @patient.phone
      tr
        td Gender
        td = @patient.gender
      tr
        td Email
        td = @patient.email

.row
  .small-6.columns
    h3 Problems
    ul
      li Problem 1
      li Lorem Ipsum
      li Dolor Sit Amet
  .small-6.columns
    h3 Medications
    ul
      li Med 1
      li Med 2
      li Med 3

.row
  .small-12.columns
    h3 Report Log
    table
      thead
        tr
          th Body Part
          th Pain Level
          th Time
      - @patient.pain_logs.each do |t|
        tr
          td = t.body_part
          td = t.pain_level
          td = t.created_at